name: mandala
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-283.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.10.0
  page_transition: ^2.0.9

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo_adaptive.png"
  min_sdk_android: 16
  adaptive_icon_background: "#471415"
  adaptive_icon_foreground: "assets/logo_adaptive.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo_adaptive.png
    - assets/logo.png
    - assets/Ilustracao.png

  fonts:
  - family: Scala
    fonts:
      - asset: assets/scala.ttf